### ISSUE TITLE
Resolver endpoint in the documentation is always returning default DID Document

### ISSUE THREAD

**Issue by venu2062** [lacchain/besu-id#1]
Resolver endpoint is always returning default values, not the updated results. 
(Please find the screenshot and text output of the result for the same DID we used for testing)

Default resolver endpoint used:
https://resolver.lacchain.net/did:lac:main:0x583f8783f0ef32a99d9e203c98b960d23c598066

We got correct resolver output using nodejs library @lacchain/did with RPCURL
'https://writer.lacchain.net'

The output using the endpoint and the actual output obtained by running our own resolver are attached.

![default resolver output](https://user-images.githubusercontent.com/3944026/135652110-9bc97a9a-2a0e-4dde-8c7a-914e8502da6c.png)

[actual resolver output.txt](https://github.com/lacchain/besu-id/files/7268539/actual.resolver.output.txt)

**Comment by sergioceron** [comment]
Hi @venu2062,

The universal resolver uses the 0xCC77A5e709cB473F49c943D9b40B989f986E5F2F DID Registry Recoverable address, so, maybe you are sending the transaction to the regular DID Registry address (0xDF1EbaE3e2318AA57CFaf11E1Dd3531D5A5AdA04). You can find the official DID registry addresses  here https://github.com/lacchain/lacchain-did-registry

**Comment by venu2062** [comment]
Hi @sergioceron,

You are right. Our mistake. Using the correct DID Registry contract address got it working.

It may be good to update the documentation saying that the DID Registry address in the URL should be substituted with the correct contract address. It may prevent future such mistakes.
